# Generated by Django 5.1.7 on 2025-04-28 14:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanghaIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the Sangha Index Page')),
            ],
            options={
                'verbose_name': 'Sangha Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SanghaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('teacher', models.ForeignKey(help_text='Select a teacher who is a Sangha member.', on_delete=django.db.models.deletion.PROTECT, related_name='sangha_pages', to='base.teacherbiography')),
            ],
            options={
                'verbose_name': 'Sangha Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
