# Generated by Django 5.1.7 on 2025-04-26 22:37

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetreatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the retreat category', max_length=255, unique=True)),
                ('display_order', models.IntegerField(default=0, help_text='Higher numbers appear first in the retreat index page.')),
            ],
            options={
                'verbose_name': 'Retreat Category',
                'verbose_name_plural': 'Retreat Categories',
                'ordering': ['-display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RetreatIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RetreatDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The start date of the retreat duration.')),
                ('end_date', models.DateField(help_text='The end date of the retreat duration.')),
                ('category', models.ForeignKey(blank=True, help_text='Category of the retreat (e.g., 7-Day Retreat)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retreat_durations', to='retreat.retreatcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('monk', 'Monk'), ('nun', 'Nun')], max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(choices=[('18-19', '18-19'), ('20-30', '20-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60-70', '60-70'), ('70-80', '70-80'), ('over 80', 'Over 80')], max_length=50)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relation', models.CharField(max_length=255)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.ForeignKey(blank=True, help_text='The current status of the registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='base.registrationstatus')),
                ('retreat_duration', models.ForeignKey(help_text='The retreat duration the user is registering for.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='retreat.retreatduration')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
            },
        ),
        migrations.CreateModel(
            name='RetreatEvent',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.baseevent')),
                ('teacher_biography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.teacherbiography')),
            ],
            options={
                'abstract': False,
            },
            bases=('base.baseevent', models.Model),
        ),
        migrations.AddField(
            model_name='retreatduration',
            name='retreat_event',
            field=modelcluster.fields.ParentalKey(help_text='The retreat event this duration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='retreat_durations', to='retreat.retreatevent'),
        ),
        migrations.CreateModel(
            name='RetreatPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('retreat_event', models.ForeignKey(blank=True, help_text='The retreat event associated with this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retreat_pages', to='retreat.retreatevent')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
