# Generated by Django 5.1.7 on 2025-04-26 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreatpage',
            name='retreat_event',
            field=models.ForeignKey(help_text='The retreat event associated with this page.', on_delete=django.db.models.deletion.CASCADE, related_name='retreat_pages', to='retreat.retreatevent'),
        ),
    ]
