# Generated by Django 5.1.7 on 2025-03-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordinator',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
