# Generated by Django 5.1.7 on 2025-04-02 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetreatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the retreat category', max_length=255, unique=True)),
                ('display_order', models.IntegerField(default=0, help_text='Higher numbers appear first in the retreat index page.')),
            ],
            options={
                'verbose_name': 'Retreat Category',
                'verbose_name_plural': 'Retreat Categories',
                'ordering': ['-display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='retreatduration',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the retreat (e.g., 7-Day Retreat)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retreat_durations', to='retreat.retreatcategory'),
        ),
    ]
