# Generated by Django 5.1.7 on 2025-04-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.CharField(choices=[('18-19', '18-19'), ('20-30', '20-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60-70', '60-70'), ('70-80', '70-80'), ('over 80', 'Over 80')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact_phone',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact_relation',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('monk', 'Monk'), ('nun', 'Nun')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
