# Generated by Django 5.1.7 on 2025-04-26 22:59

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0002_alter_retreatpage_retreat_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retreatpage',
            name='retreat_event',
        ),
        migrations.AddField(
            model_name='retreatevent',
            name='retreat_page',
            field=modelcluster.fields.ParentalKey(default=None, help_text='The retreat page this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='retreat_events', to='retreat.retreatpage'),
            preserve_default=False,
        ),
    ]
