# Generated by Django 5.1.7 on 2025-04-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0002_registration_address_registration_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
