# Generated by Django 5.1.7 on 2025-04-26 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0003_remove_retreatpage_retreat_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retreatevent',
            name='retreat_page',
        ),
        migrations.AddField(
            model_name='retreatpage',
            name='retreat_event',
            field=models.OneToOneField(default=None, help_text='The retreat event associated with this page.', on_delete=django.db.models.deletion.CASCADE, related_name='retreat_page', to='retreat.retreatevent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retreatduration',
            name='retreat_event',
            field=models.ForeignKey(help_text='The retreat event this duration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='retreat_durations', to='retreat.retreatevent'),
        ),
    ]
