# Generated by Django 5.1.7 on 2025-04-02 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0003_alter_retreatduration_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('monk', 'Monk'), ('nun', 'Nun')], max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(choices=[('18-19', '18-19'), ('20-30', '20-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60-70', '60-70'), ('70-80', '70-80'), ('over 80', 'Over 80')], max_length=50)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relation', models.CharField(max_length=255)),
                ('retreat_duration', models.ForeignKey(help_text='The retreat duration the user is registering for.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='retreat.retreatduration')),
            ],
        ),
    ]
