# Generated by Django 5.1.7 on 2025-03-25 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0003_teacherbiography_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetreatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Retreat Categories',
            },
        ),
        migrations.AddField(
            model_name='retreatpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retreats', to='retreat.retreatcategory'),
        ),
    ]
