# Generated by Django 5.1.7 on 2025-04-26 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0004_remove_retreatevent_retreat_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreatpage',
            name='retreat_event',
            field=models.OneToOneField(blank=True, help_text='The retreat event associated with this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retreat_page', to='retreat.retreatevent'),
        ),
    ]
