# Generated by Django 5.1.7 on 2025-03-25 05:41

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0004_retreatcategory_retreatpage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retreatpage',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='retreatpage',
            name='zoom_information',
        ),
        migrations.AddField(
            model_name='retreatpage',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retreatpage',
            name='zoom_room_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retreatpage',
            name='zoom_room_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AvailableRetreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('retreat_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_retreats', to='retreat.retreatpage')),
            ],
        ),
    ]
