# Generated by Django 5.1.7 on 2025-03-25 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0005_remove_retreatpage_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retreatpage',
            name='category',
        ),
        migrations.AddField(
            model_name='availableretreat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retreats', to='retreat.retreatcategory'),
        ),
    ]
