# Generated by Django 5.1.7 on 2025-04-26 23:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0006_remove_retreatpage_retreat_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreatduration',
            name='retreat_event',
            field=modelcluster.fields.ParentalKey(help_text='The retreat event this duration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='retreat_durations', to='retreat.retreatevent'),
        ),
    ]
