# Generated by Django 5.1.7 on 2025-03-28 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_retreatcategory_options_and_more'),
        ('retreat', '0008_remove_retreatpage_available_retreats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableretreat',
            name='category',
        ),
        migrations.AlterField(
            model_name='retreatpageavailableretreat',
            name='available_retreat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.availableretreat'),
        ),
        migrations.AlterField(
            model_name='retreatpagecoordinator',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.coordinator'),
        ),
        migrations.RemoveField(
            model_name='teacherbiography',
            name='image',
        ),
        migrations.AlterField(
            model_name='retreatpage',
            name='teacher_biography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.teacherbiography'),
        ),
        migrations.DeleteModel(
            name='RetreatCategory',
        ),
        migrations.DeleteModel(
            name='AvailableRetreat',
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.DeleteModel(
            name='TeacherBiography',
        ),
    ]
