# Generated by Django 5.1.7 on 2025-04-28 14:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the status (e.g., Registered, Accepted, Rejected)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the status')),
            ],
            options={
                'verbose_name': 'Registration Status',
                'verbose_name_plural': 'Registration Statuses',
            },
        ),
        migrations.CreateModel(
            name='RetreatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the retreat category', max_length=255, unique=True)),
                ('display_order', models.IntegerField(default=0, help_text='Higher numbers appear first in the retreat index page.')),
            ],
            options={
                'verbose_name': 'Retreat Category',
                'verbose_name_plural': 'Retreat Categories',
                'ordering': ['-display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ZoomInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_name', models.CharField(help_text="Name of the Zoom meeting (e.g., 'Dhamma Talk').", max_length=255)),
                ('zoom_link', models.URLField(help_text='Zoom meeting link.')),
                ('zoom_room_id', models.CharField(help_text='Zoom room ID.', max_length=255)),
                ('zoom_room_password', models.CharField(help_text='Zoom room password.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherBiography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('biography', wagtail.fields.RichTextField()),
                ('is_sangha_member', models.BooleanField(default=False, help_text='Check this box if the teacher belongs to the Sangha.')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
