# Generated by Django 5.1.7 on 2025-04-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='baseevent',
            name='zoom_meeting',
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='coordinators',
            field=models.ManyToManyField(blank=True, help_text='Coordinators for this event.', related_name='events', to='base.coordinator'),
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseevent',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
