# Generated by Django 5.1.7 on 2025-04-27 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_baseevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='zoom_meeting',
            field=models.ForeignKey(blank=True, help_text='Zoom meeting information for the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='base.zoommeetinginfo'),
        ),
    ]
